package initcmd

import (
	"bytes"
	"text/template"

	"github.com/seandheath/koboctl/internal/manifest"
)

// manifestTemplate is the annotated TOML template for koboctl.toml.
// It uses text/template syntax against a manifest.Manifest value.
// Comments explain each field to make the generated file self-documenting.
const manifestTemplate = `# koboctl.toml — generated by koboctl init
# Edit this file and run: koboctl provision

# ---------------------------------------------------------------------------
# Device
# ---------------------------------------------------------------------------
[device]
# model: device profile name. Only "libra-colour" (Kobo Libra Colour) is
# supported in v1.
model = "{{.Device.Model}}"
# mount: USB mount point on the host. Leave empty for auto-detection.
mount = ""

# ---------------------------------------------------------------------------
# KOReader — the primary e-book reader application
# ---------------------------------------------------------------------------
[koreader]
enabled = {{.KOReader.Enabled}}
# channel: "stable" (recommended) or "nightly" (latest features, less tested)
channel = "{{.KOReader.Channel}}"
# version: "latest" or a pinned release tag, e.g. "v2024.11"
version = "{{.KOReader.Version}}"

# ---------------------------------------------------------------------------
# KFMon — filesystem monitor; required dependency for KOReader and Plato
# ---------------------------------------------------------------------------
[kfmon]
enabled = {{.KFMon.Enabled}}
version = "{{.KFMon.Version}}"

# ---------------------------------------------------------------------------
# NickelMenu — adds a custom menu to Kobo's built-in reader UI (Nickel)
# ---------------------------------------------------------------------------
[nickelmenu]
enabled = {{.NickelMenu.Enabled}}
version = "{{.NickelMenu.Version}}"
{{range .NickelMenu.Entries}}
[[nickelmenu.entries]]
location = "{{.Location}}"
label    = "{{.Label}}"
action   = "{{.Action}}"
arg      = "{{.Arg}}"
{{- if .Chain}}
chain    = "{{.Chain}}"
{{- end}}
{{end}}
# Additional [[nickelmenu.entries]] blocks can be added manually above.
# See: https://github.com/pgaskin/NickelMenu#configuration

# ---------------------------------------------------------------------------
# Plato — alternative e-book reader (not fully implemented in phase 1)
# ---------------------------------------------------------------------------
[plato]
enabled = {{.Plato.Enabled}}

# ---------------------------------------------------------------------------
# Hardening — security and privacy hardening for the device
# ---------------------------------------------------------------------------
[hardening]
enabled = {{.Hardening.Enabled}}

[hardening.network]
# mode controls what outbound WiFi access is permitted:
#   "metadata-only" — KOReader metadata fetching only (recommended)
#   "offline"       — block all outbound traffic via hosts blocklist
#   "open"          — no restrictions
mode = "{{.Hardening.Network.Mode}}"
# dns_servers: CleanBrowsing Family Filter by default.
# Alternatives: OpenDNS FamilyShield (208.67.222.123), Cloudflare for Families (1.1.1.3)
dns_servers = [{{range $i, $s := .Hardening.Network.DNSServers}}{{if $i}}, {{end}}"{{$s}}"{{end}}]
block_telemetry = {{.Hardening.Network.BlockTelemetry}}
block_ota       = {{.Hardening.Network.BlockOTA}}
block_sync      = {{.Hardening.Network.BlockSync}}

[hardening.parental]
# Parental controls PIN must be set manually on the device after provisioning:
#   More -> Settings -> Accounts -> Parental Controls
# A 4-digit PIN is required. Factory reset is the only recovery if lost.
enabled      = {{.Hardening.Parental.Enabled}}
lock_store   = {{.Hardening.Parental.LockStore}}
lock_browser = {{.Hardening.Parental.LockBrowser}}

[hardening.services]
disable_telnet = {{.Hardening.Services.DisableTelnet}}
disable_ftp    = {{.Hardening.Services.DisableFTP}}
disable_ssh    = {{.Hardening.Services.DisableSSH}}

[hardening.filesystem]
# noexec_onboard is NOT SUPPORTED — all Kobo hacked software (KOReader, KFMon,
# NickelMenu, Plato) executes from the FAT32 partition. Do not change this.
noexec_onboard          = false
disable_koboroot        = {{.Hardening.Filesystem.DisableKoboRoot}}
remove_dangerous_plugins = {{.Hardening.Filesystem.RemoveDangerousPlugins}}

[hardening.privacy]
block_analytics_db = {{.Hardening.Privacy.BlockAnalyticsDB}}
hosts_blocklist    = {{.Hardening.Privacy.HostsBlocklist}}
`

// Render executes the annotated TOML template against m and returns the result.
// The output is a valid, human-readable TOML file with inline comments.
func Render(m manifest.Manifest) (string, error) {
	tmpl, err := template.New("manifest").Parse(manifestTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, m); err != nil {
		return "", err
	}
	return buf.String(), nil
}
