package initcmd

import (
	"bytes"
	"text/template"

	"github.com/seandheath/koboctl/internal/manifest"
)

// manifestTemplate is the annotated TOML template for koboctl.toml.
// It uses text/template syntax against a manifest.Manifest value.
// Comments explain each field to make the generated file self-documenting.
const manifestTemplate = `# koboctl.toml — generated by koboctl init
# Edit this file and run: koboctl provision

# ---------------------------------------------------------------------------
# Device
# ---------------------------------------------------------------------------
[device]
# model: device profile name. Only "libra-colour" (Kobo Libra Colour) is
# supported in v1.
model = "{{.Device.Model}}"
# mount: USB mount point on the host. Leave empty for auto-detection.
mount = "{{.Device.Mount}}"

# ---------------------------------------------------------------------------
# KOReader — the primary e-book reader application
# ---------------------------------------------------------------------------
[koreader]
enabled = {{.KOReader.Enabled}}
# version: "latest" or a pinned release tag, e.g. "v2024.11"
version = "{{.KOReader.Version}}"
# plugins: KOReader plugins to install by name (from a built-in registry).
# Pin a version with "name@vX.Y.Z". Available: dynamic_panelzoom, scrawl
plugins = [{{range $i, $p := .KOReader.Plugins}}{{if $i}}, {{end}}"{{$p}}"{{end}}]
# boot_into_koreader: launch KOReader automatically at power-on (via KFMon
# on_boot). Exiting KOReader returns to the normal Kobo (Nickel) home.
boot_into_koreader = {{.KOReader.BootIntoKOReader}}

# ---------------------------------------------------------------------------
# KFMon — filesystem monitor; required dependency for KOReader
# ---------------------------------------------------------------------------
[kfmon]
enabled = {{.KFMon.Enabled}}
# Version is embedded in the koboctl binary (not configurable).

# ---------------------------------------------------------------------------
# NickelMenu — adds a custom menu to Kobo's built-in reader UI (Nickel)
# ---------------------------------------------------------------------------
[nickelmenu]
enabled = {{.NickelMenu.Enabled}}
version = "{{.NickelMenu.Version}}"
{{range .NickelMenu.Entries}}
[[nickelmenu.entries]]
location = "{{.Location}}"
label    = "{{.Label}}"
action   = "{{.Action}}"
arg      = "{{.Arg}}"
{{- if .Chain}}
chain    = "{{.Chain}}"
{{- end}}
{{end}}
# Additional [[nickelmenu.entries]] blocks can be added manually above.
# See: https://github.com/pgaskin/NickelMenu#configuration

# ---------------------------------------------------------------------------
# Hardening — security and privacy hardening for the device
# ---------------------------------------------------------------------------
# Root-filesystem (/etc/*) changes can't be written over USB, so they are staged
# as .adds/koboctl/harden-*.sh scripts run at each boot via the KFMon on_boot hook.
[hardening]
# When enabled, koboctl always (regardless of the toggles below):
#   - edits .kobo/Kobo/Kobo eReader.conf: AutoUpdateEnabled=false, AutoSync=false,
#     EnableDebugServices=false, SideloadedMode=true (disables OTA + cloud sync);
#   - adds an AFTER INSERT trigger on AnalyticsEvents in .kobo/KoboReader.sqlite
#     that deletes analytics rows as they arrive (DB backed up to .koboctl-backup);
#   - removes the webbrowser/SSH/MyWebDav/send2ebook KOReader .koplugin dirs.
enabled = {{.Hardening.Enabled}}

[hardening.network]
# mode: any non-empty value (or block_telemetry) stages harden-dns.sh, which at
# boot rewrites /etc/resolv.conf to dns_servers and marks it immutable (chattr +i).
# offline/open are not yet distinct — any non-empty value just enables the lockdown.
mode = "{{.Hardening.Network.Mode}}"
# dns_servers: the nameserver lines harden-dns.sh writes into /etc/resolv.conf
# (CleanBrowsing Family Filter by default). The file is made immutable so udhcpc
# cannot overwrite it on WiFi connect.
# Alternatives: OpenDNS FamilyShield (208.67.222.123), Cloudflare for Families (1.1.1.3)
dns_servers = [{{range $i, $s := .Hardening.Network.DNSServers}}{{if $i}}, {{end}}"{{$s}}"{{end}}]
# block_telemetry also enables the harden-dns.sh DNS lockdown (uses dns_servers).
# The /etc/hosts telemetry blocklist is the separate privacy.hosts_blocklist toggle.
block_telemetry = {{.Hardening.Network.BlockTelemetry}}

# Parental controls cannot be set over USB — configure a 4-digit PIN and the
# Store/Browser locks on the device: More -> Settings -> Accounts -> Parental Controls.

[hardening.services]
# harden-devmode.sh runs each boot. disable_telnet: pkill telnetd + strip telnet
# from /etc/inetd.conf(.local) + HUP inetd (closes the passwordless-root "devmodeon"
# backdoor). disable_ftp: strip ftp from /etc/inetd.conf + HUP inetd.
disable_telnet = {{.Hardening.Services.DisableTelnet}}
disable_ftp    = {{.Hardening.Services.DisableFTP}}

[hardening.filesystem]
# noexec_onboard is NOT SUPPORTED — all Kobo hacked software (KOReader, KFMon,
# NickelMenu) executes from the FAT32 partition. Do not change this.
noexec_onboard   = false
# disable_koboroot: replace .kobo/KoboRoot.tgz (the package the firmware auto-extracts
# as root on boot) with a same-named directory so no rogue update can be applied;
# harden-koboroot.sh re-establishes the guard after the legit first-boot update.
disable_koboroot = {{.Hardening.Filesystem.DisableKoboRoot}}

[hardening.privacy]
# hosts_blocklist stages harden-hosts.sh: appends 0.0.0.0 entries to /etc/hosts for
# Kobo/Rakuten telemetry, Google Analytics, DoubleClick, Hotjar, and ipinfodb
# (idempotent, marker-guarded).
hosts_blocklist = {{.Hardening.Privacy.HostsBlocklist}}
`

// Render executes the annotated TOML template against m and returns the result.
// The output is a valid, human-readable TOML file with inline comments.
func Render(m manifest.Manifest) (string, error) {
	tmpl, err := template.New("manifest").Parse(manifestTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, m); err != nil {
		return "", err
	}
	return buf.String(), nil
}
