package cmd_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pelletier/go-toml/v2"
	"github.com/seandheath/koboctl/cmd"
	"github.com/seandheath/koboctl/internal/manifest"
)

// runInit runs the koboctl init command with the given args and stdin input.
// Returns stdout, stderr, and any execution error.
func runInit(t *testing.T, args []string, stdinInput string) (stdout, stderr string, err error) {
	t.Helper()
	root := cmd.NewRootCommand()

	outBuf := &bytes.Buffer{}
	errBuf := &bytes.Buffer{}
	root.SetOut(outBuf)
	root.SetErr(errBuf)
	root.SetIn(strings.NewReader(stdinInput))
	root.SetArgs(args)

	execErr := root.Execute()
	return outBuf.String(), errBuf.String(), execErr
}

func TestInitCommand_DefaultsWritesParsableToml(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "koboctl.toml")

	_, _, err := runInit(t, []string{"init", "--defaults", "--output", outPath}, "")
	if err != nil {
		t.Fatalf("init --defaults: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("output file not written: %v", err)
	}

	var m manifest.Manifest
	if err := toml.Unmarshal(data, &m); err != nil {
		t.Fatalf("generated TOML unparseable: %v\n---\n%s", err, data)
	}
	if !m.KOReader.Enabled {
		t.Error("KOReader should be enabled in defaults")
	}
	if !m.Hardening.Enabled {
		t.Error("Hardening should be enabled in defaults")
	}
}

func TestInitCommand_RefusesOverwrite(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "koboctl.toml")

	// Create existing file.
	if err := os.WriteFile(outPath, []byte("existing"), 0o644); err != nil {
		t.Fatal(err)
	}

	_, _, err := runInit(t, []string{"init", "--defaults", "--output", outPath}, "")
	if err == nil {
		t.Error("expected error when file exists without --force")
	}
	if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("error should mention existing file, got: %v", err)
	}

	// Verify original content is unchanged.
	data, _ := os.ReadFile(outPath)
	if string(data) != "existing" {
		t.Error("original file should not be modified")
	}
}

func TestInitCommand_ForceOverwrites(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "koboctl.toml")

	if err := os.WriteFile(outPath, []byte("old content"), 0o644); err != nil {
		t.Fatal(err)
	}

	_, _, err := runInit(t, []string{"init", "--defaults", "--force", "--output", outPath}, "")
	if err != nil {
		t.Fatalf("init --force: %v", err)
	}

	data, _ := os.ReadFile(outPath)
	if string(data) == "old content" {
		t.Error("--force should overwrite the file")
	}
	// Must be parseable TOML.
	var m manifest.Manifest
	if err := toml.Unmarshal(data, &m); err != nil {
		t.Fatalf("overwritten file not valid TOML: %v", err)
	}
}

func TestInitCommand_InteractiveChildSafe(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "koboctl.toml")

	// Simulate: accept all defaults (bare Enter) until hardening section,
	// then answer "y" to child-safe shortcut.
	// Questions in order:
	//   model, koreader?, channel, version, nickelmenu?, plato?, hardening?, child-safe?
	stdinInput := "\n\n\n\n\n\n\ny\n"

	_, _, err := runInit(t, []string{"init", "--output", outPath}, stdinInput)
	if err != nil {
		t.Fatalf("interactive init: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("output not written: %v", err)
	}

	var m manifest.Manifest
	if err := toml.Unmarshal(data, &m); err != nil {
		t.Fatalf("interactive TOML unparseable: %v\n---\n%s", err, data)
	}
	if !m.Hardening.Enabled {
		t.Error("hardening should be enabled")
	}
	// ChildSafeDefaults sets mode to "offline"
	if m.Hardening.Network.Mode != "offline" {
		t.Errorf("child-safe mode = %q, want offline", m.Hardening.Network.Mode)
	}
}

func TestInitCommand_OutputContainsComments(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "koboctl.toml")

	runInit(t, []string{"init", "--defaults", "--output", outPath}, "") //nolint:errcheck

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}
	out := string(data)

	comments := []string{
		"generated by koboctl init",
		"NOT SUPPORTED",
		"CleanBrowsing",
	}
	for _, want := range comments {
		if !strings.Contains(out, want) {
			t.Errorf("expected comment %q in output", want)
		}
	}
}
